# coding=utf-8
'''
Mappatura dei Log Sankyo ICT3Q8 (Performance & Errori)
@author: selkala (2025)
versione 1.0
License: MIT (see LICENSE file)

'''


# PERFORMANCE LOG
# Formato: (Offset Byte, Lunghezza Byte, "Descrizione")
# Nota: Tutti i contatori sono interi a 32-bit (4 byte) Big Endian
PERFORMANCE_MAP = [
    (0, 4, "Card pass"),
    (4, 4, "Captures operation"),
    (8, 4, "Magnetic head pass"),
    (12, 4, "Track #1: mag-cards read free of errors"),
    (16, 4, "Track #1: mag-cards read with errors"),
    (20, 4, "Track #1: mag-cards write free of errors"),
    (24, 4, "Track #1: mag-cards write with errors"),
    (28, 4, "Track #2: mag-cards read free of errors"),
    (32, 4, "Track #2: mag-cards read with errors"),
    (36, 4, "Track #2: mag-cards write free of errors"),
    (40, 4, "Track #2: mag-cards write with errors"),
    (44, 4, "Track #3: mag-cards read free of errors"),
    (48, 4, "Track #3: mag-cards read with errors"),
    (52, 4, "Track #3: mag-cards write free of errors"),
    (56, 4, "Track #3: mag-cards write with errors"),
    (60, 4, "IC-cards: activation free of errors"),
    (64, 4, "IC-cards: activation with errors"),
    (66, 4, "IC-cards: non-supported IC-card"),
    (68, 4, "IC-cards: communication errors"),
    (72, 4, "SAM1: activation free of errors"),
    (74, 4, "SAM1: activation with errors"),
    (76, 4, "SAM1: non-supported SAM"),
    (78, 4, "SAM1: communication errors"),
    (80, 4, "SAM2: activation free of errors"),
    (84, 4, "SAM2: activation with errors"),
    (86, 4, "SAM2: non-supported SAM"),
    (88, 4, "SAM2: communication errors"),
    (90, 4, "SAM3: activation free of errors"),
    (94, 4, "SAM3: activation with errors"),
    (96, 4, "SAM3: non-supported SAM"),
    (98, 4, "SAM3: communication errors"),
    (100, 4, "SAM4: activation free of errors"), 
    (104, 4, "SAM4: activation with errors"),
    (106, 4, "SAM4: non-supported SAM"),
    (108, 4, "SAM4: communication errors"),
    (110, 4, "SAM5-SAMn: activation free of errors"),
    (114, 4, "SAM5-SAMn: activation with errors"),
    (116, 4, "SAM5-SAMn: non-supported SAM"),
    (118, 4, "SAM5-SAMn: communication errors"),
    (120, 4, "Shutter: error-free operations"),
    (124, 4, "Shutter: errors"),
    (128, 4, "ICC contact: error-free operations"),
    (132, 4, "ICC contact: errors"),
]

# ERROR LOG CODES
# Mappa Codice Errore (Stringa) -> Descrizione
ERROR_MAP = {
    "00": "To shows that received command was undefined.",
    "01": "To show command parameter error.",
    "02": "The reception of the command that impossible to implementation.",
    "03": "To shows that the command to the hardware that does not exist was received.",
    "04": "To show that error data was included in command.",
    "05": "To show that a command, which requires the card movement, was executed before IC contacts were released from the card.",
    "06": "ICRW does not have keys that decipher the data.",
    "10": "To show that the card was not carried to the specific location.",
    "11": "To show that status signal for 'shutter open' is not received while shutter is open.",
    "12": "To show that sensor(s) are damaged or more that one card is inside ICRW.",
    "13": "To show that the card longer than 92mm is inserted into ICRW.",
    "14": "To show that the card shorter than 78mm is inserted into ICRW.",
    "15": "To show that data in EEPROM is damaged.",
    "16": "To show that card staying inside the ICRW was moved up to the point where status request information changes.",
    "17": "To show that the card was not carried to the specific location.",
    "18": "To show that shutter open/close detection sensor (SW2) and card width check sensor (SW1) are not operating correctly.",
    "19": "To show that a card was not inserted from the rear, even if 10 seconds had passed after the execution of BACK ENTRY command.",
    "20": "To show that track has parity error.",
    "21": "To show that read error has happened in Multiple magnetic read command.",
    "22": "To show that write error is detected through write / verify procedure.",
    "23": "To show that only SS, ES, LRC are contained in the track (no retry).",
    "24": "To show that the card has no magnetic track (no retry).",
    "25": "To show that quality error (Jitter, Preamble, Post amble) has happened in write verify.",
    "26": "To show that the track has no SS.",
    "27": "To show that the track has no ES.",
    "28": "To show that the track has LRC error.",
    "29": "To show that the discordance of write data has happened in write verify.",
    "30": "To show that power down (or power cut in short instant) is detected .",
    "31": "R.F.U",
    "32": "R.F.U",
    "40": "To show that the card was pulled out from ICRW through entrance gate when CAPTURE command is being executed.",
    "41": "Failure at IC Contact solenoid or sensor ICD",
    "43": "Card could not be set to IC contact position / Failure at sensor PDI.",
    "45": "ICRW lost sight of the card when ICRW completed to carry the card to the rear position during the card acceptance.",
    "46": "To show that the ejected card has not been withdrawn during execution of Monitoring for removal command.",
    "49": "R.F.U",
    "50": "Retract counter overflow. / Capture counter overflow.",
    "51": "To show that Motor error has happened, through start / stop check in Initialize command.",
    "52": "PowerEject ERROR",
    "53": "R.F.U",
    "54": "R.F.U",
    "55": "R.F.U",
    "56": "R.F.U",
    "57": "R.F.U",
    "58": "R.F.U",
    "59": "R.F.U",
    "60": "To show that there found abnormal condition on the power-line (Vcc) of ICC/SAM.",
    "61": "The receiving error of ATR. ICRW has disconnected already.",
    "62": "To show that the specified protocol does not agree with that of ICC/SAM.",
    "63": "In case T=1 cards, after ATR receiving, IFS exchange is failed. ICRW detects time out.",
    "64": "In case T=1 cards, after ATR receiving, IFS exchange is failed. ICRW detects protocol error.",
    "65": "HOST tried to communicate with IC card without card activation.",
    "66": "ICRW tried to activate with ICC/SAM, but the card returned ATR, which is not supported.",
    "69": "ICRW tried to activate with ICC/SAM, but the card returned ATR, which does not match EMV.",
    "70": "Failure at F-ROM operation.",
    "71": "Firmware of User program code area is wrong.",
    "74": "R.F.U",
    "76": "R.F.U",
    "95": "R.F.U",
    "96": "R.F.U",
    "99": "R.F.U",
    "B0": "Received the other command before executing Initialize command.",
}